version: "3.8"

networks:
  shared-bridge:
    name: shared-bridge
    driver: bridge

services:
  portainer-pve:
    image: portainer/portainer-ce:latest
    networks:
      - shared-bridge
    volumes:
      - ${DATA_APPS}/portainer:/data
      - ${DATA_PVE}:/pve
    ports:
      - 9000:9000
    restart: always
    command:
      - --log-level=DEBUG
      - --admin-password=${DEFAULT_PASSWORD}
      - --templates="https://raw.githubusercontent.com/technorabilia/portainer-templates/main/lsio/templates/templates-2.0.json"

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 81:81/tcp
    volumes:
      - ${DATA_APPS}/nginx-proxy-manager/data:/data
      - ${DATA_APPS}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /pve/fast-logs/nginx-proxy-manager:/var/log
    restart: always
